# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the entire application code
COPY . .

# Build the React application
RUN npm run build

# Expose the port your React application will run on (usually 3000)
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "start"]
